#!/bin/bash

# Play the main radio station
play_main_station() {
    mpv http://stream.peaceradio.com:8000/high
}

# Play the Quran radio station
play_quran_station() {
    mpv http://stream.peaceradio.com:8000/quran/high
}

# Color variables
green='\e[32m'
red='\e[31m'
blue='\e[34m'
clear='\e[0m'

# Color functions
color_green() {
    echo -ne $green$1$clear
}

color_blue() {
    echo -ne $blue$1$clear
}

# Radio menu
menu() {
    echo -ne "
                                                                                                      
█ ▄▄  ▄███▄   ██   ▄█▄    ▄███▄       █▄▄▄▄ ██   ██▄   ▄█ ████▄ 
█   █ █▀   ▀  █ █  █▀ ▀▄  █▀   ▀      █  ▄▀ █ █  █  █  ██ █   █ 
█▀▀▀  ██▄▄    █▄▄█ █   ▀  ██▄▄        █▀▀▌  █▄▄█ █   █ ██ █   █ 
█     █▄   ▄▀ █  █ █▄  ▄▀ █▄   ▄▀     █  █  █  █ █  █  ▐█ ▀████ 
 █    ▀███▀      █ ▀███▀  ▀███▀         █      █ ███▀   ▐       
  ▀             █                      ▀      █                 
               ▀                             ▀ "Tune 2 Reality"


    $(color_green '1)') Play Main Radio Station
    $(color_green '2)') Play Quran Radio Station
    $(color_green '0)') Exit
    $(color_blue 'Choose an Option:') "

    read -r option
    case $option in
        1) play_main_station ;;
        2) play_quran_station ;;
        0) exit 0 ;;
        *) echo -e $red"Wrong option."$clear ;;
    esac

    menu
}

# Start the radio menu
menu

