#!/bin/bash

# Check if mpv is installed
if ! command -v mpv &> /dev/null; then
    echo -e $red"mpv is not installed. Please install it to use this script."$clear
    exit 1
fi

# Timer function
start_timer() {
    start_time=$(date +%s)
}

update_timer() {
    local current_time
    current_time=$(date +%s)
    elapsed=$((current_time - start_time))
}

# Play the main radio station
play_main_station() {
    start_timer
    mpv http://stream.peaceradio.com:8000/high
}

# Play the Quran radio station
play_quran_station() {
    start_timer
    mpv http://stream.peaceradio.com:8000/quran/high
}

# Color variables
green='\e[32m'
red='\e[31m'
blue='\e[34m'
cyan='\e[36m'
clear='\e[0m'

# Color functions
color_green() {
    echo -ne $green$1$clear
}

color_blue() {
    echo -ne $blue$1$clear
}

color_cyan() {
    echo -ne $cyan$1$clear
}

# Radio menu
menu() {
    clear
    echo -ne "
                                                                                                      
█ ▄▄  ▄███▄   ██   ▄█▄    ▄███▄       █▄▄▄▄ ██   ██▄   ▄█ ████▄ 
█   █ █▀   ▀  █ █  █▀ ▀▄  █▀   ▀      █  ▄▀ █ █  █  █  ██ █   █ 
█▀▀▀  ██▄▄    █▄▄█ █   ▀  ██▄▄        █▀▀▌  █▄▄█ █   █ ██ █   █ 
█     █▄   ▄▀ █  █ █▄  ▄▀ █▄   ▄▀     █  █  █  █ █  █  ▐█ ▀████ 
 █    ▀███▀      █ ▀███▀  ▀███▀         █      █ ███▀   ▐       
  ▀             █                      ▀      █                 
               ▀                             ▀ "Tune 2 Reality"


    $(color_green '1)') Play Main Radio Station
    $(color_green '2)') Play Quran Radio Station
    $(color_green '0)') Exit
    $(color_blue 'Choose an Option:') "

    read -r option
    case $option in
        1) play_main_station ;;
        2) play_quran_station ;;
        0)
            update_timer
            clear
            echo -e "\n$(color_cyan "Elapsed Time: $((elapsed / 60))m $((elapsed % 60))s")"
            echo -e "\nExiting..."
            exit 0
            ;;
        *) echo -e $red"Invalid option. Please try again."$clear; sleep 2 ;;
    esac

    menu
}

# Start the radio menu
menu

